version: '3'
services:
  whisper_gpu:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'whisper-gpu'
    working_dir: '/app'
    volumes:
      - ./audio:/app/audio/
      - ./output:/app/output/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all 